config/routes.rb
Rails.application.routes.draw do
  
 
  resources :user_cryptos, only: [:create, :destroy]
  devise_for :users
  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_crypto', to: 'cryptos#search'
  get 'my_friends', to: 'users#my_friends'
  get 'search_friend', to: 'users#search'
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crypto.rb
class Crypto < ApplicationRecord

  has_many :user_cryptos
  has_many :users, through: :user_cryptos

validates :name, :ticker, presence: true

  def self.new_lookup(ticker_symbol)
    client = IEX::Api::Client.new(
      publishable_token: Rails.application.credentials.iex_client[:IEX_API_PUBLISHABLE_TOKEN],
      endpoint: 'https://cloud.iexapis.com/v1'
    )
    begin
      new(ticker: ticker_symbol, name: client.crypto(ticker_symbol).symbol,
          last_price: client.crypto(ticker_symbol).ask_price)
    rescue => exception
      return nil
    end
  end

  def self.check_db(ticker_symbol)
    where(ticker: ticker_symbol).first
  end

end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_cryptos
  has_many :cryptos, through: :user_cryptos
  has_many :friendships
  has_many :friends, through: :friendships

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def already_tracked?(ticker_symbol)
    crypto = Crypto.check_db(ticker_symbol)
    return false unless crypto

    cryptos.where(id: crypto.id).exists?
  end

  def under_limit?
    cryptos.count < 10
  end

  def can_track?(ticker_symbol)
    under_limit? && !already_tracked?(ticker_symbol)
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name

    email
  end

  def self.search(param)
    param.strip!
    param.downcase!
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless to_send_back
    to_send_back
  end

  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  def self.matches(field_name, param)
    where("lower(#{field_name}) like ?", "%#{param}%")
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end


  def not_friend_with?(id_of_friend)
    !self.friends.where(id: id_of_friend).exists?
  end
end

app/models/user_crypto.rb
class UserCrypto < ApplicationRecord
  belongs_to :user
  belongs_to :crypto
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name,:last_name])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name,:last_name])
    end

end

app/controllers/cryptos_controller.rb
class CryptosController < ApplicationController
  def search
    if params[:crypto].present?
      @crypto = Crypto.new_lookup(params[:crypto])
      if @crypto
        respond_to do |format|
          format.js { render partial: 'users/result' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = 'Please enter a valid symbol to search'
          format.js { render partial: 'users/result' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = 'Please enter the symbol to search'
        format.js { render partial: 'users/result' }
      end
    end
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    friend = User.find(params[:friend])
    current_user.friendships.build(friend_id: friend.id)
    if current_user.save 
    
      flash[:notice] = "Added friend"
    else
      flash[:alert] = "There was something wrong"

    end
    redirect_to my_friends_path
  end

  def destroy
    friendship = current_user.friendships.where(friend_id: params[:id]).first
    friendship.destroy
    flash[:notice] = "Stopped being friend"
    redirect_to my_friends_path
  end
end

app/controllers/user_cryptos_controller.rb
class UserCryptosController < ApplicationController
  def create
    crypto = Crypto.check_db(params[:ticker])
    if crypto.blank?
      crypto = Crypto.new_lookup(params[:ticker])
      crypto.save
    end
    @user_crypto = UserCrypto.create(user: current_user, crypto: crypto)
    flash.now[:notice] = "#{crypto.name} was successfully added to your portfolio"
    redirect_to my_portfolio_path
  end

  def destroy

    crypto = Crypto.find(params[:id])
    user_crypto = UserCrypto.where(user_id: current_user.id, crypto_id: crypto.id).first
    user_crypto.destroy
    flash.now[:notice] = "#{crypto.name} was successfully removed from your portfolio"
    redirect_to my_portfolio_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @tracked_crypto = current_user.cryptos
    @user = current_user
  end

  def my_friends
    @friends = current_user.friends
  end

def show

  @user = User.find(params[:id])
  @tracked_crypto = @user.cryptos
end

  def search
    if params[:friend].present?
      @friends = User.search(params[:friend])
      @friends = current_user.except_current_user(@friends)
      if @friends
        respond_to do |format|
          format.js { render partial: 'users/friend_result' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = 'Could not find the user'
          format.js { render partial: 'users/friend_result' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = 'Please enter something to search'
        format.js { render partial: 'users/friend_result' }
      end
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cryptos_helper.rb
module CryptosHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/user_cryptos_helper.rb
module UserCryptosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cryptos/_list.html.erb
<% if !@tracked_crypto.empty? %>
<div class="row">
  <div class="col-9">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">Ticker</th>
          <th scope="col">Name</th>
          <th scope="col">Price</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
      <% @tracked_crypto.each do |crypto|%>
        <tr>
          <th scope="row"><%= crypto.ticker%></th>
          <td><%= !!crypto.name ? crypto.name : "N/A"%></td>
          <td><%= !!crypto.last_price ? crypto.last_price : "N/A"%></td>
          
          <td>

 <%if current_user.can_track?(crypto.ticker)%>
      <%= link_to "Add to my portfolio", user_cryptos_path(user: current_user, ticker: crypto.ticker), class: "btn btn-xs btn-success", method: :post%>
    <%elsif current_user.id != @user.id%>
      <span class="badge badge-secondary">
        Already tracked
        <% if !current_user.under_limit? %>
        to limit 
        <% else %>
        this crypto
        <% end %>
      </span>
    <% end %>

          <% if current_user.id == @user.id %>
          <%= link_to "Remove", user_crypto_path(crypto), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-sm btn-warning"%>
          <% end %>
          
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>
<% end %>

app/views/friends/_list.html.erb
<div class="row">
  <div class="col-9">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">Email</th>
          <th scope="col">First Name</th>
          <th scope="col">Last Name</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
      <% @friends.each do |friend|%>
        <tr>
          <th scope="row"><%= friend.email%></th>
          <td><%= !!friend.first_name ? friend.first_name : "N/A"%></td>
          <td><%= !!friend.last_name ? friend.first_name : "N/A"%></td>
          <td><%= link_to "View Profile", user_path(friend), class: "btn btn-sm btn-success"%>
          <%= link_to "Remove", friendship_path(friend), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-sm btn-warning"%></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="bg-dark text-center">
  <!-- Copyright -->
  <div class="text-center p-3 mt-2 text-light" ">
    © 2021 Copyright:
    <a class="text-light" href="https://www.aratori.net/">Aratori.net</a>
  </div>
  <!-- Copyright -->
</footer>

app/views/layouts/_messages.html.erb
<% if notice %>
	<div class='alert alert-success'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= notice %>
	</div>
<% end %>

<% if alert %>
	<div class='alert alert-danger'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= alert %>
	</div>
<% end %>

app/views/layouts/_navigations.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-5">
  <div class="container">
    <%= link_to "CryptoTracker", root_path, class: 'navbar-brand'%>
    <% if user_signed_in? %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item <%= 'active' if request.path == my_portfolio_path%>">
            <%= link_to "My Portfolio", my_portfolio_path, class: "nav-link"%>
          </li>
          <li class="nav-item <%= 'active' if request.path == my_friends_path %>">
             <%= link_to "My Friends", my_friends_path, class: "nav-link"%>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Profile
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to edit_user_registration_path, class: "dropdown-item" do%>
                <%= fa_icon 'edit'%> Edit profile
              <%end%>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
        
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item mr-1 pt-2">
            <%= fa_icon 'user' %> <%= current_user.full_name%>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, class: "btn  btn-xs mr-1",method: :delete%>
          </li>
        </ul>
      
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
   <%= render "layouts/navigations"%>
    <div class="container">
   <%= render "layouts/messages"%>
      <%= yield %>
      
    </div>
    <%= render "layouts/footer"%>
  </body>
</html>

app/views/users/_friend_result.html.erb
<div class="d-inline-block">
  <%= render "layouts/messages"%>
</div>
<%if @friends %>
  <div class="card card-header d-inline-block mb-4">
    <table class="col-md-12">
      <tbody>
        <% @friends.each do |friend|%>
          <tr>
            <td>    <strong>Email:</strong> <%= !!friend.email ? friend.email : "N/A"%> </td>
            <td>  <strong>First Name:</strong> <%= !!friend.first_name ? friend.first_name : "N/A"%> </td>
            <td>   <strong>Last Name:</strong> <%= !!friend.last_name ? friend.last_name : "N/A"%> </td>
            <td>   <strong>Profile: </strong> <%= link_to "View Profile", user_path(friend), class: "btn btn-xs btn-success"%>
              <% if current_user.not_friend_with?(friend.id) %>
                <%= link_to "Add friend", friendships_path(friend: friend), class: "btn btn-xs btn-success", method: :post%>
              <% else %>
                
                  <%= link_to "Added", friendship_path(friend), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-xs btn-secondary"%>
                
              <% end %>
            </td>
          <% end %>
        </tr>
      </tbody>
    </table>
  </div>
<% end %>

app/views/users/_friend_result.js.erb
document.querySelector("#result").innerHTML = "<%= j render 'users/friend_result.html'%>"

app/views/users/_result.html.erb
<div class="d-inline-block">
  <%= render "layouts/messages"%>
</div>
<%if @crypto%>
  <div class="card card-header d-inline-block mb-4">
    <strong>Symbol: </strong><%= !!@crypto.ticker ? @crypto.ticker : "N/A"%>
    <strong>Name: </strong><%= !!@crypto.name ? @crypto.name : "N/A"%>
    <strong>Price: </strong><%= !!@crypto.last_price ? @crypto.last_price : "N/A"%>
    <%if current_user.can_track?(@crypto.ticker)%>
      <%= link_to "Add to my portfolio", user_cryptos_path(user: current_user, ticker: @crypto.ticker), class: "btn btn-xs btn-success", method: :post%>
    <%else%>
      <span class="badge badge-secondary">
        Already tracked
        <% if !current_user.under_limit? %>
        to limit 
        <% else %>
        this crypto
        <% end %>
      </span>
    <% end %>
  </div>
<% end %>

app/views/users/_result.js.erb
document.querySelector("#result").innerHTML = "<%= j render 'users/result.html'%>"

app/views/users/my_friends.html.erb
<h1>Friends</h1>
<div class="pt-5">
  <p>Search for friends</p>
  <%= form_tag search_friend_path, remote: true, method: :get do%>
    <div class="form-group row">
      <div class="col-sm-9 p-0">
        <%= text_field_tag :friend, params[:friend], placeholder: "Friend's name", autofocus: true, class: "form-control form-control-lg shadow-none rounded-0 ml-2"%>
      </div>
      <div class="col-sm-3 p-0">
        <%= button_tag type: :submit, class: "btn btn-success rounded-0" do%>
          <%= fa_icon 'search 2x'%>
        <%end%>
      </div>
    </div>
  <% end %>
</div>
<div id="result"></div>

<% if !@friends.empty? %>
<%= render "friends/list"%>
<% else %>
<p>You have no friend!</p>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>
<div class="pt-5">
  <p>Search Cryptocurrency</p>
  <%= form_tag search_crypto_path, remote: true, method: :get do%>
    <div class="form-group row">
      <div class="col-sm-9 p-0">
        <%= text_field_tag :crypto, params[:crypto], placeholder: "Cryptocurrency Symbol", autofocus: true, class: "form-control form-control-lg shadow-none rounded-0 ml-2"%>
      </div>
      <div class="col-sm-3 p-0">
        <%= button_tag type: :submit, class: "btn btn-success rounded-0" do%>
          <%= fa_icon 'search 2x'%>
        <%end%>
      </div>
    </div>
  <% end %>
</div>
<div id="result"></div>

<% if !@tracked_crypto.empty?%>
<%= render "cryptos/list"%>
<% else %>
<p>You have nothing in your portfolio!</p>
<% end %>

app/views/users/show.html.erb
<h2>User Details</h2>
<div class="card card-header d-inline-block mb-4">
  <table class="col-md-12">
    <tbody>
      <tr>
        <td>    <strong>Email:</strong> <%= !!@user.email ? @user.email : "N/A"%> </td>
        <td>  <strong>First Name:</strong> <%= !!@user.first_name ? @user.first_name : "N/A"%> </td>
        <td>   <strong>Last Name:</strong> <%= !!@user.last_name ? @user.last_name : "N/A"%> </td>
        <td>   
          <% if current_user.not_friend_with?(@user.id) %>
            <%= link_to "Add friend", friendships_path(friend: @user), class: "btn btn-xs btn-success", method: :post%>
          <% else %>
            <%= link_to "Already added friend", friendship_path(@user), method: :delete, data: {confirm: "Are you sure?"}, class: "badge badge-xs badge-secondary"%>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

<% if !@tracked_crypto.empty?%>
<%= render "cryptos/list"%>
<% else %>
<p> <%= @user.email %> has nothing in its portfolio!</p>
<% end %>

app/views/welcome/index.html.erb
<% if user_signed_in? %>
 
<h1>Welcome to CryptoTracker Application</h1>

<p>Thank you for your registration.</p>
<p>Find your cryptocurrency and track !</p>



<% else %>
  <div class="center jumbotron">
    <h1>Welcome to the CryptoTracker Application</h1>
    <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>